START TRANSACTION;
USE CARS;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE makers;
DROP TABLE car_names;
DROP TABLE cars;
DROP TABLE continents;
DROP TABLE countries;
DROP TABLE models;
SET FOREIGN_KEY_CHECKS=1;
COMMIT;

